### ISSUE TITLE
VCPU Shutdown Request on Windows 10 Pro, Intel i5 8th Gen, 8GB RAM

### ISSUE THREAD

**Issue by jmdsenanayake** [intel/haxm#194]
**Describe the Bug**

Summary: 

**Host Environment**

* HAXM version: Tried with 7.3.2 and 7.4.1

* Host OS version: Windows 10 Pro version

* Host OS architecture: x86\_64

* Host CPU model:  Core i5-8250U

* Host RAM size: 8GB

* (Optional) Host computer model: HP Probook G5

**Guest Environment**

* Android Emulator or QEMU version: 

* Guest OS version: Tried with Lolipop, Nougut, Oreo

* Guest OS architecture: tried with both x86 and x86\_64

**To Reproduce**

1. emulator -avd Nexus_5X_API_27 -netspeed full -netdelay none
2. 
3. 

**Expected Behavior**

Expectation: Should up & run the emulator

**Reproducibility**

100%

**Diagnostic Information**

Host crash dump: VCPU Shutdown Request (Repeatedly)

HAXM log: 

Android Emulator or QEMU log: 

Screenshots: 

**Additional context**

None

**Comment by huang03jun** [comment]
Would you get log on Windows, https://github.com/intel/haxm/blob/master/docs/manual-windows.md#Capturing%20driver%20logs

**Comment by jmdsenanayake** [comment]
> Would you get log on Windows, https://github.com/intel/haxm/blob/master/docs/manual-windows.md#capturing-driver-logs , and what is your emulator version? You could get the version in Android Studio. About steps, do you mean the emulator crash just after you launch it, by emulator -avd Nexus_5X_API_27? Guest(Emulator) Crash, not Host(Windows) Crash?

thanks for the reply. only thing in the powershell is showing as "VCPU Shutdown request" repeatedly. Yes the emulator crashed. not windows. 

emulator is working fine if i used ARM based architecture which is very slow.

**Comment by HaHoYou** [comment]
Would you get log on Windows, https://github.com/intel/haxm/blob/master/docs/manual-windows.md#capturing-driver-logs , and what is your emulator version? You could get the version in Android Studio.

**Comment by jmdsenanayake** [comment]
Issue has been resolved with https://github.com/intel/haxm/releases/tag/v7.5.1 HAXM v 7.5.1 release

**Comment by dennisbappert** [comment]
The issue is still open for me with 7.5.1

**Comment by coxuintel** [comment]
> The issue is still open for me with 7.5.1

Which version of emulator you are using?
Does the issue still happen if only set only one vCPU?

**Comment by freelancerliketodev** [comment]
Have the same issue
![TAXI-T082020_024246](https://user-images.githubusercontent.com/70055590/101422399-475c9d80-38ff-11eb-9897-3eb94616b793.png)

**Comment by wayne-ma** [comment]
Hi @freelancerliketodev , could you provide the details configuration when met this issue? Eg. HAXM version, host OS version, HW config, Android image version.

**Comment by dr-emmett-brown** [comment]
Hi, I also have the same problem (100% reproducable):
**Host:**
CPU i5 
RAM: 16 GB 
Windows 7
HAXM 7.6.5
Android emulator version 30.3.5.0 (build_id 7033400)
**Guest environment:**
Android 11.0 - tested with both "Emulated performance" options: software and hardware
CPUs: tested 1 and 2
**Command to reproduce:**
emulator -avd Pixel_3a_API_30_x86
