### ISSUE TITLE
Can't install HAXM 7.5.2 on Windows 10 Pro 1903

### ISSUE THREAD

**Issue by marcelovicentegc** [intel/haxm#236]
**Describe the Bug**

Summary: I can't install HAXM succesfully on my machine. I disabled Hyper-V, Windows Hypervisor Platform and Windows Sandbox features, restarted my PC several times and verified if virtualization was enabled on UEIF, which it is, as well as checked if the Memory integrity tick was off, which again, it is, and if the Credential-Guard and HVCI were enabled, which aren't, and I still face the same error both from the installer provided here and from Android Studio itself: `This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed. Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information.`. I'm out of directions right now. Any help or feedback will be really appreciated.

**Host Environment**

* HAXM version: 7.5.2 (I also tried version 7.3.0)

* Host OS version: Windows 10 Pro version 1903

* Host OS architecture: x86\_64

* Host CPU model: Intel Core i5-7200U (https://ark.intel.com/content/www/us/en/ark/products/95443/intel-core-i5-7200u-processor-3m-cache-up-to-3-10-ghz.html)

* Host RAM size: 16 GB

* (Optional) Host computer model: Dell Inspiron 15 3567

**Expected Behavior**

Expectation: Be able to install HAXM successfully.

**Comment by wcwang** [comment]
Thanks for your report. Have you ever tried the steps in [Disabling Hyper-V on Windows 10](https://github.com/intel/haxm/blob/master/docs/manual-windows.md)? If this approach cannot resolve your issue, could you confirm whether your Dell laptop has the same issue as described in #226?

**Comment by marcelovicentegc** [comment]
@wcwang , I had followed that manual and I still couldn't achieve what I was looking for. #226 was useful, though. I had the WSL enabled, and as soon as I disabled it, I could install HAXM. Out of curiosity, how much effort would it take to make possible to have both HAXM and Hyper-V running simultaneously?

**Comment by wcwang** [comment]
@marcelovicentegc, thanks for your question. At current stage, it is impossible to have both HAXM and Hyper-V coexist. This is because HAXM is a Type 2 hypervisor, while Hyper-V is a Type 1 hypervisor. In order to install HAXM properly, both Hyper-V and WSL2 features have to be disabled.

**Comment by devrnt** [comment]
If anyone else is having issues with this problem, I highly suggest to take a look at https://developer.android.com/studio/run/emulator-acceleration#vm-windows

**Comment by congjinruo** [comment]
in my case, you should disabled hyperv and **windows sandbox**  and **pure restart** your machine.

**Comment by Csaba8472** [comment]
Run into the same issue, I had to downgrade WSL from 2 to 1 to be able to install and use haxm. Hope it helps.

**Comment by wayne-ma** [comment]
We summarized a guide for the conflicts on Windows, you can take it for reference when meeting such issue,
https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows#Tips_and_Tricks

**Comment by yusufkhan07** [comment]
Turning off `Hyper-V` & `Windows Hypervisor Platform` worked for me while `WSL` in on.

**Comment by wayne-ma** [comment]
@yusufkhan07 , I guess you used WSL not WSL2. Actually WSL dose not conflict HAXM.

**Comment by dalisoft** [comment]
Same issue, what we do need to make it work?

**Comment by wcwang** [comment]
@dalisoft, thanks for your comments. Just as previous discussions, you need to turn off both Hyper-V and Windows Hypervisor Platform from Windows Features. Then HAXM can be installed and work on Windows.

**Comment by emedez** [comment]
This used to be the problem with VirtualBox too prior to version 6.1.16, but now this issue has been solved by VirtualBox and it is now able to run side by side with WSL2. Can the same thing be done with HAXM also, so that it installs and run together with WSL2?

**Comment by sglbl** [comment]
When will Haxm work when Wsl-2 ( which requires Hyper-V ) is activated ?

**Comment by Kyrluckechuck** [comment]
So I see this as marked as closed, but the problem still exists, is there any update on if we'll be able to use WSL2 without conflicting with HAXM?

**Comment by idl0r** [comment]
ping
